name: PR Unit Tests

on:
  push:
    branches: [ 'div', 'main' ]
  pull_request:
    branches: [ 'div', 'main' ]

jobs:
  unit-test:
    name: Run Unit Tests on PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew test